name: Check uptime of website
on:
  schedule:
    - cron: "* * * * *"

jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matchai/heads-up@master
        with:
          url: https://www.kevincunningham.co.uk
          access_token: ${{ secrets.ACCESS_TOKEN }}
